language: php
sudo: false

php:
  - 7.0
fast_finish: true

before_script:
  - composer install -v

script:
  - phpunit -vvv --coverage-clover ./build/logs/clover.xml

after_script:
  -  php bin/coveralls -vvv