language: php
sudo: false

php:
  - 5.5
  - 5.6
  - hhvm
  - nightly
allow_failures:
  - php: nightly
  - php: hhvm
fast_finish: true

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - ./bin/phpspec run