language: php
sudo: false

php:
  - 5.6
  - nightly
matrix:
  allow_failures:
    - php: nightly
fast_finish: true

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; else PHPUNIT_FLAGS=""; fi
  - composer install -v

script:
  - phpunit -v $PHPUNIT_FLAGS

after_script:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then php bin/coveralls -v; fi