language: php
sudo: false

php:
  - 7.0
fast_finish: true

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; else PHPUNIT_FLAGS=""; fi
  - composer install -v

script:
  - phpunit -v $PHPUNIT_FLAGS

after_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then php bin/coveralls -v; fi